### ISSUE TITLE
Not able to integrate the Server Api with frontend in nextjs

### ISSUE THREAD

**Issue by krishFred** [apollo-server-integrations/apollo-server-integration-next#212]
I'm facing The integration issue Where it leads to the 404 whenever i try with useQuery
  Here is the simple setup I was trying to execute [Github link](https://github.com/krishFred/nextjs-graphql)

**Comment by martinnabhan** [comment]
There are two reasons your Route Handler can't be compiled and Next.js returns a 404.

1. You are trying to read a file that doesn't exist.

Since `__dirname` points to `.next/server/app/api/graphql` (at least when using `next dev`) you need to change `path.resolve(__dirname, "@/utils/graphql/server/schema.graphql")` to `path.resolve(__dirname, "../../../../../src/utils/graphql/server/schema.graphql")`.

Also, you can't use TypeScript paths (`@/`) when using `readFileSync`.

2. `type message = String` isn't valid GQL.

To return a string from a query you need to change your schema like this:
```gql
type Query {
  hello: String
}
```

**Comment by krishFred** [comment]
Event after the changes you stated it was still leading 404 page not found error ` Response not successful: Received status code 404` Is there any project setup you might provide for the reference, It could find the handler there
